### ISSUE TITLE
Theoretical question

### ISSUE THREAD

**Issue by JacksonFurrier** [thibsej/unbalanced_gromov_wasserstein#1]
Given two mm-spaces <img src="https://render.githubusercontent.com/render/math?math=(X, \mu, d_{X}), (Y, \nu, d_{Y})"> and assuming <img src="https://render.githubusercontent.com/render/math?math=X, Y"> are both Euclidean and the metrics are identical. Is it true that the Unbalanced Gromov-Wasserstein in this case will "fall back" - nonetheless, my calculations show that it will be <img src="https://render.githubusercontent.com/render/math?math=\leq"> - to Unbalanced Wasserstein? My gut tells me that this is true, since <img src="https://render.githubusercontent.com/render/math?math=\int_{X^{2} \times Y^{2}} \lambda (|d_{X} - d_{Y})|) \dots"> (equation 6 in [Unbalanced Gromov-Wasserstein](https://arxiv.org/abs/2009.04266) paper) will be zero a.e. since the metrics equate, however I haven't been able to prove it.

**Comment by thibsej** [comment]
Hi @JacksonFurrier,
I am not sure of what you exactly mean by "falling" back. I guess it means that if you assume the two mm-spaces are defined on the same space, then UGW is equivalent to the unbalanced Wasserstein (UW) distance. Based on [this paper](https://arxiv.org/pdf/1208.0434.pdf) (Section 2.2), best I can say is that you should be able to prove UGW <= 2 * UW. But it cannot be an equality, for instance take a measure and its translation, for which UGW=0 (because a translation is an isometry) but UW is not.
Did I properly answered your question ?

**Comment by JacksonFurrier** [comment]
Sorry for the belated answer! Thank you I see it now. I think what got me confused was the expression lambda(|d_X - d_Y|), where I thought if the metric spaces are both Euclidean so the metrics equate (e.g.: trying to compute UGW between 2D images on the same "grid") then the latter form in the integral <img src="https://render.githubusercontent.com/render/math?math=\int_{X^{2} \times Y^{2}} \lambda (|d_{X} - d_{Y})|) \dots"> would result in identically 0.

**Comment by thibsej** [comment]
Hi @JacksonFurrier,
It's great if I answered your question ! Then I close this issue.
